name: "Build, Test, and Release Main Branch"

on:
    push:
        branches:
          - main
        paths:
          - '**.rs'

jobs:
    rust:
        name: "Rust"
        uses: ./.github/workflows/rust.yml
        secrets:
          client_id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
        