name: Build and Test Rust Code

on:
  pull_request:
    branches:
      - main
  
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
    build-and-test:
        name: Build and Test
        environment: cicd
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
            
            - name: Install protobuf
              run: sudo apt install -y protobuf-compiler && protoc --version
            
            - name: cargo build
              run: cargo build --all-targets --release

            - name: Login to Azure
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            
            - name: Write config
              run: $GITHUB_WORKSPACE/target/release/get-config ${{ secrets.CONFIG_STORE_NAME }} > $GITHUB_WORKSPACE/.env

            - name: cargo test
              run: cargo test --release

            - name: Upload Archive
              uses: actions/upload-artifact@v3
              with:
                name: nueces-homies-bot
                path: |
                  target/release/get-config


            
            

            
