name: "Build and Test Pull Request"

on:
    pull_request:
        branches: 
          - main
        # paths:
        #   - '**.rs'
    push:
        branches:
          - main
        # paths:
        #   - '**.rs'

jobs:
    build-and-test:
        name: "Build and Test"
        environment: cicd
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
            
            - name: Install protobuf
              run: app install -y protobuf-compiler && protoc --version
            
            - name: Build
              run: cargo build --tests --verbose

            - name: Login to Azure
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            
            - name: Write config
              run: $GITHUB_WORKSPACE/target/get-config > $GITHUB_WORKSPACE/.env

            - name: Test
              run: cargo test --verbose
            
