name: "Build and Test Rust Code"

on:
    workflow_call:
      

permissions:
  id-token: write
  contents: read

jobs:
    build-and-test:
        name: "Build and Test"
        environment: cicd
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
            
            - name: Install protobuf
              run: sudo apt install -y protobuf-compiler && protoc --version
            
            - name: Build
              run: cargo build --all-targets --release

            - name: Login to Azure
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            
            - name: Write config
              run: $GITHUB_WORKSPACE/target/release/get-config ${{ secrets.CONFIG_STORE_NAME }} > $GITHUB_WORKSPACE/.env

            - name: Test
              run: cargo test --release
            
